sudo: false
services:
- docker
env:
  matrix:
  - TOXENV=27 CODECOV=py
  - TOXENV=34 CODECOV=py
  - TOXENV=35 CODECOV=py
  - TOXENV=36 CODECOV=py
  - TOXENV=37 CODECOV=py
  - TOXENV=flake8

script:
- docker run -v $PWD:/pepper -e "CODECOV=$CODECOV" -e "TOXENV=$TOXENV" -e "CODECOV_TOKEN=$CODECOVE_TOKEN" -ti --rm gtmanfred/pepper:latest /runtests.sh
