sudo: false
services:
- docker
language: python
cache: pip
services:
- docker

before_install:
- pyenv versions

install:
- pip install tox

matrix:
  include:
  - env: TOXENV=27 CODECOV=py
    python: 2.7
  - env: TOXENV=34 CODECOV=py
    python: 3.4
  - env: TOXENV=35 CODECOV=py
    python: 3.5
  - env: TOXENV=36 CODECOV=py
    python: 3.6
  - env: TOXENV=37 CODECOV=py
    python: 3.7
  - env: TOXENV=flake8
    python: 3.6

script:
- if [[ -n $CODECOV ]]; then docker run -v $PWD:/pepper -ti --rm gtmanfred/pepper:latest tox -c /pepper/tox.ini -e "${CODECOV}${TOXENV}",coverage; fi
- if [[ -z $CODECOV ]]; then docker run -v $PWD:/pepper -ti --rm gtmanfred/pepper:latest tox -c /pepper/tox.ini -e "${CODECOV}${TOXENV}"; fi

after_success:
- if [[ $CODECOV== "py" ]]; then tox -e codecov; fi
