sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
env:
  TOXENV=py
addons:
  apt:
    packages:
    - openssh-server

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=flake8

before_install:
  - pyenv versions

install:
  - pip install tox

script:
  - tox

after_success:
  - if [[ $TOXENV == "py" ]]; then tox -e coverage,codecov; fi
