sudo: false
services:
- docker
language: python
cache: pip
python:
- 3.6
env:
  matrix:
  - TOXENV=27 CODECOV=py
  - TOXENV=34 CODECOV=py
  - TOXENV=35 CODECOV=py
  - TOXENV=36 CODECOV=py
  - TOXENV=37 CODECOV=py
  - TOXENV=flake8

install:
- pip install tox

script:
- docker run -v $PWD:/pepper -ti --rm gtmanfred/pepper:latest tox --workdir /pepper -e "${CODECOV}${TOXENV}"

after_success:
- if [[ $CODECOV == "py" ]]; then tox -e coverage,codecov; fi
