sudo: false
services:
- docker
language: python
cache: pip
services:
- docker

before_install:
- pyenv versions

install:
- pip install tox

env:
  - PY=py27
  - PY=py34
  - PY=py35
  - PY=py36
  - PY=py37
  - SALT=v2017.7.9
  - SALT=v2018.8.4
  - SALT=v2019.2.0
  - BACKEND=cherrypy
  - BACKEND=tornado

script:
  - docker run -v $PWD:/pepper -ti --rm gtmanfred/pepper:latest tox -c /pepper/tox.ini -e "${PY}-${BACKEND}-${SALT}"

jobs:
  include:
    - stage: test
      python: 2.7
      script: docker run -v $PWD:/pepper -ti --rm gtmanfred/pepper:latest tox -c /pepper/tox.ini -e flake8
    - stage: test
      python: 2.7
      script: docker run -v $PWD:/pepper -ti --rm gtmanfred/pepper:latest tox -c /pepper/tox.ini -e coverage

after_success:
- sudo chown $USER .tox/
- if [[ $CODECOV == "py" ]]; then tox -e codecov; fi
